name: Wing Provider Specific

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.setdirs.outputs.dirs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get list of directories
        id: setdirs
        shell: bash
        run: |
          dirs=$(ls -d examples/*/ | sed 's/\/$//' | jq -R -s -c 'split("\n")[:-1]')
          matrix=$(echo "{ \"directory\": $dirs }")
          echo $matrix
          echo "::set-output name=dirs::$matrix"

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.examples) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install winglang globally
        run: npm install -g winglang
      - name: Execute wing test in matrix directory
        run: cd ${{ matrix.directory }} && wing test --debug --target tf-aws main.w
